name: Run Vorpal on Changed Files

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Run Vorpal on Changed Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: files
      uses: jitterbit/get-changed-files@v1

    - name: Run Vorpal on changed files
      run: |
        chmod +x bin/vorpal_linux_x64
        for file in ${{ steps.files.outputs.all }}; do
          echo "Running Vorpal on $file"
          bin/vorpal_linux_x64 -s "$file" -r r.csv
          cat r.csv >> results.csv
        done
        if [ -s results.csv ]; then
          echo "Vorpal results for changed files: $(cat results.csv | grep -v 'Language,RuleId')"
          exit 1
        else
          echo "No Vorpal results for changed files"
        fi

