name: Run Vorpal on Changed Files

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Run Vorpal on Changed Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: files
      uses: jitterbit/get-changed-files@v1

    - name: Run Vorpal on changed files
      run: |
        chmod +x bin/vorpal_linux_x64
        for file in ${{ steps.files.outputs.all }}; do
          bin/vorpal_linux_x64 -s "$file" -r r.csv
          cat r.csv >> results.csv
        done
        if [ -s results.csv ]; then
          gh pr comment $PR_URL --body "Vorpal results for changed files: $(cat results.csv)"
          exit 1
        else
          gh pr comment $PR_URL --body "No Vorpal results for changed files"
        fi
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

