name: Run Vorpal on Changed Files

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Run Vorpal on Changed Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: files
      uses: jitterbit/get-changed-files@v1

    - name: Review Dog Setup
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest

    - name: Run Vorpal on changed files
      run: |
        export REVIEWDOG_GITHUB_API_TOKEN="${{ github.token }}"
        chmod +x bin/vorpal_linux_x64
        for file in ${{ steps.files.outputs.all }}; do
          echo "Running Vorpal on $file"
          bin/vorpal_linux_x64 -s "$file" -r r.errorformat
          cat r.errorformat >> results.errorformat
        done
        if [ -s results.errorformat ]; then
          echo "Vorpal results for changed files:" 
          cat results.errorformat | reviewdog -f=golint -name=vorpal -reporter=github-pr-check -diff="git diff HEAD^"
          exit 1
        else
          echo "No Vorpal results for changed files"
        fi

