name: Run Vorpal on Changed Files

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-vorpal:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get list of changed files
      id: changed-files
      run: |
        echo "files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.source-extension$')" >> $GITHUB_OUTPUT

    - id: files
      uses: jitterbit/get-changed-files@v1

    - name: Run Vorpal on changed files
      run: |
        for file in ${{ steps.files.outputs.all }}; do
          bin/vorpal -s "$file" -r r.csv
          cat r.csv >> results.csv
        done
        if [ -s results.csv ]; then
          gh pr comment $PR_URL --body "Vorpal results for changed files: $(cat results.csv)"
        fi
