name: Post welcome comment
on:
  pull_request:
    branches: ["main"]
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Welcome branch $BRANCH with commit $COMMIT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          BRANCH: ${{ github.head_ref }}
          COMMIT: ${{ github.envent.after }}

